region: 204

monitoring_profiles:
  fizjo_markiewicz:
    doctor: "Marcin Markiewicz"
    specialty_id: 163
    date_from: "2026-04-27"
    date_to: "2026-05-15"
    time_from: "08:00"
    time_to: "12:00"
    interval_min: 600
    interval_max: 1200
    auto_book: true
